# Generated by Django 4.2 on 2024-10-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='prompt',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
