# Generated by Django 4.2 on 2024-10-08 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtester', '0002_strategy_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='user',
        ),
    ]
