# Generated by Django 4.2 on 2024-10-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtester', '0003_remove_strategy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
